mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
# Widoki posta.

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',     views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

<!-- Post -->
{% block content %}
  <h1>{{ post.title }}</h1>
  <!-- Tytuł posta -->
	<p class="date">
		Opublikowany {{ post.publish }} przez {{ post.author }}
		<!-- Dane Posta -->
	</p class="tresc">
		{{ post.body|markdown }}
		<!-- Treść Posta -->
	<p>
		<a href="{% url "blog:post_share" post.id %}">
		<!-- Hyperlink -->
			Udostępnij post
			<!-- Treść hyperlinku-->
		</a>
	</p>
	
	
	<!-- Ilość komentarzy -->
	{% with comments.count as total_comments %}
	<!-- Funkcja liczona przez pc-->
		<h2>
			{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
			<!-- Y komentarz-->
		</h2>
	{% endwith %}
	
	<!-- Lista komentarzy -->
	{% for comment in comments %}
	<!-- iteracja przez komentarze -->
		<div class="comment">
			<p>
				Komentarz 
				{{ forloop.counter }}
				<!-- Który komentarz -->
				dodany przez
				{{ comment.name }}
				{{ comment.created }}
				<!-- Informacje o komentarzu -->
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
	<!-- Jeżeli Pusty -->
		<p>Nie ma jeszcze żadnych komentarzy.</p>
	{% endfor %}
	
	
	{% if new_comment %}
	<!-- Jeżeli istnieje obiekt -->
		<h2>
			Twój komentarz został dodany
		</h2>
	{% else %}
		<h2>
			Dodaj nowy komentarz
		</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<!-- Zabezpieczenie przed atakami -->
			<p>
				<input type="submit" value="Dodaj komentarz">
			</p>
		</form>
	{% endif %}
	
	
	<h2>
		Podobne posty
	</h2>
	{% for post in similar_posts %}
		<p> 
			<a href="{{ post.get_absolute_url }}">
				{{ post.title }}
			</a>
		</p>
	{% empty %}
		Nie ma podobnych postów.
	{% endfor %}
	
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}Mój blog{% endblock %}

{% block content %}
	<h1>
		Mój blog
		<!-- Tytuł wyswietlany na kżdej stronie z listą postów -->
	</h1>
	
	{% if tag %}
	<!-- Jeżeli tag != none -->
		<h2>
			Posty oznaczone tagiem "{{ tag.name }}"
			<!-- Napis na każdej liście z okresłonym tagiem -->
		</h2>
	{% endif %}
	
	{% for post in posts %}
	<!-- Iteracja -->
		<h2>
		
			<a href="{{ post.get_absolute_url }}">
			<!-- Link do posta -->
				{{ post.title }}
				<!-- Nazwa posta -->
			</a>
			
				<p class="tags">
					Tagi:
					{% for tag in post.tags.all %}
						<a href="{% url "blog:post_list_by_tag" tag.slug %}">
							{{ tag.name }}
						</a>
						{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
		</h2>
		<p class="date">
			Opublikowany {{ post.publish }} przez {{ post.author }}
		</p>
		{{ post.body|markdown|truncatewords_html:30 }}
		<!-- truncatewords_html skraca ilosć wyrazów -->
	{% endfor %}
	{% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Szukaj{% endblock %}

{% block content %}

    {% if "query" in request.GET %}
        <h1>
            Posty zawierające "{{ query }}"
        </h1>
        <h3>
            Znaleziono {{ total_results }} wynik{{ total_results|pluralize:"i" }}
        </h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h4>
                {{ post.body|truncatewords:5 }}
            {% endwith %}
        {% empty %}
            <p>
                Brak wyników dla podanego zapytania.
            </p>
        {% endfor %}
        <p>
            <a href="{% url "blog:post_search" %}">
                Szukaj ponownie
            </a>
        </p>
    {% else %}
        <h1>
            Szukaj postów
        </h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Szukaj">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Wiadomość e-mail została wysłana</h1>
    <p>      
	Wysłanie posta "{{ post.title }}" do {{ cd.to }} zakończyło się sukcesem.
    </p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Wyślij wiadomość e-mail">
    </form>
  {% endif %}
{% endblock %}