mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
# Widoki posta.

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',     views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/blog/templates/blog/base.html
{% load blog_tags %}
<!-- Załaduj znacznik szblonu -->
{% load static %}
<!-- Załaduj pliki statyczne -->

<!DOCTYPE html>

<html>

<head>
  <title>
	{% block title %}
	{% endblock %}
	</title>
  <link rel="stylesheet" href="{% static "blogg/blog.css" %}" type="text/css"/>
  <!-- Skorzytaj z pliku css -->
</head>


<body>
  <div class="body">
	{% block content %}
	{% endblock %}
	<!-- Główna zawartość strony -->
  </div>
  
  <div class="sidebar">
  <!-- Jeżeli wpiszemy id przestanie współdziać z css -->
	<h2> Mój blog </h2>
	<p> To jest mój blog. Dotychczas opublikowałem {% total_posts %} postów. </p>
	<p>
		<a href="{% url "blog:post_feed" %}">Subskrybuj kanał</a>
	</p>
	<h3>Najnowsze posty</h3>
	{% show_latest_posts 3 %}
	
	<h3>Najczęściej komentowane posty</h3>
	{% get_most_commented_posts as most_commented_posts %}
	<ul>
		{% for post in most_commented_posts %}
			<li>
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</li>
		{% endfor %}
	</ul>
  </div>
  </body>

</html>